### ISSUE TITLE
Per-footer: ABN isn't supposed to be implemented as click-to-call. It is not a phone number.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Action-Asbestos#51]
![image](https://cloud.githubusercontent.com/assets/11186313/10900403/35ad1016-821a-11e5-9c3f-14fb2b2ecdc0.png)

**Comment by roseliesromeo** [comment]
Still made a click to call

**Comment by maehtitan** [comment]
Issue still recurring for It is still clickable in mobile

**Comment by Santosh-titan** [comment]
I don't understand why its showing for you, there is no link for ABN. For me its not showing for any device.

**Comment by roseliesromeo** [comment]
It still made click to call in S4.  Already cleaded cache/data.
![image](https://cloud.githubusercontent.com/assets/11186313/11081670/aff690f0-8859-11e5-8d86-54612df274d2.png)

**Comment by Santosh-titan** [comment]
Please clear your browser cache and try to click on ABN

**Comment by roseliesromeo** [comment]
Cleared cache/data for many times and issue is still reproducible.
ABN is still made click to call.
Click on the ABN in mobile device.

**Comment by Santosh-titan** [comment]
I just confirmed with @jonathan regarding this issue, its working fine in mobile device. 
here is his comment "I can see in the code that it's not a link and on my device it wasn't click to call so I see no reason why the bug can't be closed."

**Comment by roseliesromeo** [comment]
Issue exists in Samsung S4 only not in iTouch  and iPad air.
![image](https://cloud.githubusercontent.com/assets/11186313/11175103/73a847ba-8c69-11e5-8078-350256b69d9c.png)
