### ISSUE TITLE
General: FOUC exists.  All banner images are displayed on page load.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Action-Asbestos#53]
![image](https://cloud.githubusercontent.com/assets/11186313/10900894/8e143f58-8220-11e5-91c4-9e6e3f6394b3.png)

**Comment by maehtitan** [comment]
Recurring issue, try disabling all your JS obviously banner got no style by default
![image](https://cloud.githubusercontent.com/assets/13363508/11030124/e77c44a6-8706-11e5-9b64-8d3a116661e6.png)


Tried disabling JS on this site ang there will be a loading display not all the images displayed
![image](https://cloud.githubusercontent.com/assets/13363508/11030165/1957f786-8707-11e5-8591-093d5b7a7981.png)
