### ISSUE TITLE
News page: Description should allow 10 lines before it is shortened.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Action-Asbestos#63]
![image](https://cloud.githubusercontent.com/assets/11186313/10903053/902a5c8a-8240-11e5-8ecb-26015a2b992b.png)

**Comment by roseliesromeo** [comment]
It reached 11 lines now

**Comment by Santosh-titan** [comment]
It has only 10 lines see this screenshot.
![line-count](https://cloud.githubusercontent.com/assets/13828562/10989236/c1c4213c-846a-11e5-8210-34ac28690e61.png)

**Comment by roseliesromeo** [comment]
How about this?
![image](https://cloud.githubusercontent.com/assets/11186313/10990009/59d9486c-8489-11e5-96c4-6b99a9d022f6.png)
