### ISSUE TITLE
Phone Numbers - Mobile: Incorrect area code when clicking the Phone numbers, it should 2 digits only not 3

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Action-Asbestos#73]
![image](https://cloud.githubusercontent.com/assets/13363508/11030752/165ce074-870b-11e5-879b-1cf9e0a2d3d9.png)

**Comment by Santosh-titan** [comment]
It will take like this only. you can check with other site http://alitaconstructions.stage.titanweb.com.au/

**Comment by roseliesromeo** [comment]
I don't think so.  Parentheses should've been stripped.
Reference:
http://toplinefoods.stage.titanweb.com.au/contact-us/
http://barchetta.stage.titanweb.com.au/contact-us/
![image](https://cloud.githubusercontent.com/assets/11186313/11055322/37f676b8-87b1-11e5-9e37-5ef1d3b2f243.png)

**Comment by Santosh-titan** [comment]
I don't know about this, But thanks for giving me the example link. This issue has been fixed

**Comment by roseliesromeo** [comment]
Not fixed for mobile.
